### ISSUE TITLE
tt.tag() function failed

### ISSUE THREAD

**Issue by ruoyu-qian** [paudan/opennlp_python#2]
I downloaded apache-opennlp-1.9.1-bin.zip from [http://apache.lauf-forum.at/opennlp/opennlp-1.9.1/](url) and put it on my local computer under this directory: C:\Users\EI8193\Desktop\Python\openNLP. I also downloaded the model en-pos-maxent.bin from [http://opennlp.sourceforge.net/models-1.5/](url) and put it under C:\Users\EI8193\Desktop\Python\openNLP\models.

Here is my python code.

`from nltk_opennlp.taggers import OpenNLPTagger
import os

os.getcwd()
#os.chdir("C:/Users/EI8193/Desktop/Python")
#os.getcwd()

tt = OpenNLPTagger(language='en',
                   path_to_bin='./openNLP/apache-opennlp-1.9.1/bin',
                   path_to_model=os.path.join('./openNLP/models', 'en-pos-maxent.bin'))
phrase = 'Pierre Vinken , 61 years old , will join the board as a nonexecutive director Nov. 29 .'
sentence = tt.tag(phrase)`

I got an error when I tried to run `sentence = tt.tag(phrase)` saying OSError: OpenNLP command failed!

Could you help me with this?

Thank you so much!

**Comment by paudan** [comment]
It could be a problem with recent versions of Apache OpenNLP (this library was developed and tested with OpenNLP 1.8.0). I ran tests with `tox`, using v1.8.0, and it seems to work fine even with different versions of Python. As far as I know, there were significant changes in recent versions of OpenNLP API. I might update the library to support new OpenNLP versions in the future, but for now, I suggest to use v1.8.0.

**Comment by ruoyu-qian** [comment]
@paudan I tried on both v1.8.0 and v1.5.3, but I still got the same error. I'm using python 3.7, not sure if it impacts anything.

**Comment by paudan** [comment]
@Ruoyu-Qian I think I have found the problem - the library could not communicate with OpenNLP under Windows environment, as one of the `subprocess.Popen` params is not supported there. After removing it, all should work well - I ran multiple tests and everything seems to be working perfectly with Python 3.5/3.6, v3.7 should not be a problem as well.
