### ISSUE TITLE
Extract Entities

### ISSUE THREAD

**Issue by sajukassim** [paudan/opennlp_python#3]
How can we extract the Names from this .. eg. ('Pierre Vinken': 'PERSON')
  (PERSON Pierre/NNP Vinken/NNP)
  ,/PUNC
  (NP 61/CD years/NNS)
  (ADJP old/JJ)
  ,/PUNC
  (VP will/MD join/VB)
  (PERSON Martin/NNP Vinken/NNP)
  (PP as/IN)
  (NP a/DT nonexecutive/JJ director/NN)
  (NP Nov./NNP 29/CD)
  ./PUNC)

**Comment by paudan** [comment]
The output of `parse` function is NLTK parse tree, so you can easily use indexing to extract entities:

```
cp = OpenNLPChunker(path_to_bin=os.path.join('/path/to/opennlp/installation', 'bin'),
                 path_to_chunker=os.path.join('/path/to/opennlp/models', 'en-chunker.bin'))
parsed = cp.parse(sentence)
print(parsed[0])
```

will output:

`ParentedTree('NP', [('61', 'CD'), ('years', 'NNS')])`

Second level indices would return words with their tags, e.g. `parsed[0][0]` would return `('61', 'CD')`,
