### ISSUE TITLE
Could not download Opennlp 

### ISSUE THREAD

**Issue by k1nn1** [paudan/opennlp_python#4]
Could not download opennlp since apache nlp isn't downloading. Is there a way to get pip to install apche nlp and its models instead of doing the same manually?

**Comment by k1nn1** [comment]
I found the answer but on running the following code:
from nltk_opennlp.taggers import OpenNLPTagger

tt = OpenNLPTagger(language='en',
                    path_to_bin=os.path.join('/path/to/opennlp/installation', 'bin'),
                    path_to_model=os.path.join('/path/to/opennlp/models', 'en-pos-maxent.bin'))
phrase = 'Pierre Vinken , 61 years old , will join the board as a nonexecutive director Nov. 29 .'
sentence = tt.tag(phrase)

I get this error:
Unable to find the Apache OpenNLP run file!
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-c35d87d5e1e7> in <module>()
      5                     path_to_model=os.path.join('/path/to/opennlp/models', 'en-pos-maxent.bin'))
      6 phrase = 'Pierre Vinken , 61 years old , will join the board as a nonexecutive director Nov. 29 .'
----> 7 sentence = tt.tag(phrase)

~\Anaconda3\lib\site-packages\nltk_opennlp\taggers.py in tag(self, sentences)
     67         # Run the tagger and get the output
     68         gc.collect()
---> 69         p = Popen([self._opennlp_bin, "POSTagger", self._model_path],
     70                   shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE, universal_newlines=True)
     71         (stdout, stderr) = p.communicate(_input)

AttributeError: 'OpenNLPTagger' object has no attribute '_opennlp_bin'

What do I do?

**Comment by paudan** [comment]
Downloading `Apache OpenNLP` automatically might be a good idea, as newer versions seem to have significant changes in API, and they are not supported yet. Did you try to use Apache OpenNLP 1.8, as that was the version which I used for testing?

**Comment by k1nn1** [comment]
No, I'm using the new version 1.9.1. I will try with older version. Thanks!
