### ISSUE TITLE
Tagger does not work

### ISSUE THREAD

**Issue by itsmemala** [paudan/opennlp_python#7]
I have implemented the sample code for tagger but I get a weird output - [('', '')]. 
I've checked the installations and the paths and they seem fine. 
I'm using Apache-opennlp-1.9.2

**Comment by itsmemala** [comment]
Same issue with Apache-opennlp-1.8.4

**Comment by paudan** [comment]
I just ran tests with Apache OpenNLP 1.8.4, and all of them passed successfully. Could you provide sample code or input used to get such output?

**Comment by paudan** [comment]
I also added script to automate OpenNLP and model files download for this repository. By default they will be downloaded to the repo root directory (you would need to clone it). then you could also check if tagger is working by running tests in tests.py file
